// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7K-Jq7aoVkCxz5JnBpMPJkTjv2NsgvuY',
    appId: '1:443940014510:web:e3068f2e9abb6cd9ede03f',
    messagingSenderId: '443940014510',
    projectId: 'hotel-360-3d510',
    authDomain: 'hotel-360-3d510.firebaseapp.com',
    storageBucket: 'hotel-360-3d510.appspot.com',
    measurementId: 'G-ZTDH22NPVW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJQaSxTBwYRG4ALr38zZZVUx4bFLQO6YQ',
    appId: '1:443940014510:android:d5bab6ebcb197208ede03f',
    messagingSenderId: '443940014510',
    projectId: 'hotel-360-3d510',
    storageBucket: 'hotel-360-3d510.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBgwnLbpOUtGiP2QdPb8rQTWpLr6VcPf0k',
    appId: '1:443940014510:ios:ca7df6f265f78ac5ede03f',
    messagingSenderId: '443940014510',
    projectId: 'hotel-360-3d510',
    storageBucket: 'hotel-360-3d510.appspot.com',
    iosBundleId: 'com.example.hotelApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBgwnLbpOUtGiP2QdPb8rQTWpLr6VcPf0k',
    appId: '1:443940014510:ios:496d68dd4cd2cf32ede03f',
    messagingSenderId: '443940014510',
    projectId: 'hotel-360-3d510',
    storageBucket: 'hotel-360-3d510.appspot.com',
    iosBundleId: 'com.example.hotelApp.RunnerTests',
  );
}
